// Code generated by MockGen. DO NOT EDIT.
// Source: ../nettest/proto/example.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	proto "github.com/lj-211/go-test-example/nettest/proto"
	grpc "google.golang.org/grpc"
	reflect "reflect"
)

// MockHelloClient is a mock of HelloClient interface
type MockHelloClient struct {
	ctrl     *gomock.Controller
	recorder *MockHelloClientMockRecorder
}

// MockHelloClientMockRecorder is the mock recorder for MockHelloClient
type MockHelloClientMockRecorder struct {
	mock *MockHelloClient
}

// NewMockHelloClient creates a new mock instance
func NewMockHelloClient(ctrl *gomock.Controller) *MockHelloClient {
	mock := &MockHelloClient{ctrl: ctrl}
	mock.recorder = &MockHelloClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHelloClient) EXPECT() *MockHelloClientMockRecorder {
	return m.recorder
}

// SayHello mocks base method
func (m *MockHelloClient) SayHello(ctx context.Context, in *proto.HelloReq, opts ...grpc.CallOption) (*proto.HelloRes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SayHello", varargs...)
	ret0, _ := ret[0].(*proto.HelloRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SayHello indicates an expected call of SayHello
func (mr *MockHelloClientMockRecorder) SayHello(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SayHello", reflect.TypeOf((*MockHelloClient)(nil).SayHello), varargs...)
}

// MockHelloServer is a mock of HelloServer interface
type MockHelloServer struct {
	ctrl     *gomock.Controller
	recorder *MockHelloServerMockRecorder
}

// MockHelloServerMockRecorder is the mock recorder for MockHelloServer
type MockHelloServerMockRecorder struct {
	mock *MockHelloServer
}

// NewMockHelloServer creates a new mock instance
func NewMockHelloServer(ctrl *gomock.Controller) *MockHelloServer {
	mock := &MockHelloServer{ctrl: ctrl}
	mock.recorder = &MockHelloServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHelloServer) EXPECT() *MockHelloServerMockRecorder {
	return m.recorder
}

// SayHello mocks base method
func (m *MockHelloServer) SayHello(arg0 context.Context, arg1 *proto.HelloReq) (*proto.HelloRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SayHello", arg0, arg1)
	ret0, _ := ret[0].(*proto.HelloRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SayHello indicates an expected call of SayHello
func (mr *MockHelloServerMockRecorder) SayHello(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SayHello", reflect.TypeOf((*MockHelloServer)(nil).SayHello), arg0, arg1)
}
